# Copyright 2023 Robert Bosch GmbH
#
# SPDX-License-Identifier: Apache-2.0

---
openapi: 3.0.0
info:
  title: Channel
paths:
  /Channel:
    get:
      responses:
        '200':
          description: ''
          content:
            text/yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Channel'
components:
  schemas:
    Channel:
      type: object
      description: A channel definition.
      properties:
        name:
          type: string
          description: The name of the channel, used when connecting this channel to the SimBus.
        alias:
          type: string
          description: The alias of the channel, used when the channel name will be determined elsewhere.
        expectedModelCount:
          type: integer
          description: Indicates how many models are expected to connect to this channel (used by SimBus only).
        selectors:
          $ref: 'metadata.yaml#/components/schemas/Labels'
        annotations:
          $ref: 'metadata.yaml#/components/schemas/Annotations'
