# Copyright 2023 Robert Bosch GmbH
#
# SPDX-License-Identifier: Apache-2.0

---
openapi: 3.0.0
info:
  title: Metadata
paths:
  /Annotations:
    get:
      responses:
        '200':
          description: ''
          content:
            text/yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Annotations'
  /Labels:
    get:
      responses:
        '200':
          description: ''
          content:
            text/yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Labels'
  /ObjectMetadata:
    get:
      responses:
        '200':
          description: ''
          content:
            text/yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ObjectMetadata'
components:
  schemas:
    Annotations:
      type: object
      description: Non identifying information (i.e. information specific to the object itself).
      additionalProperties: {}
    Labels:
      type: object
      description: Identifying information used to identify objects within the system (e.g. giving a specific 'label' to an object).
      additionalProperties:
        type: string
    ObjectMetadata:
      type: object
      description: Information relating to an object.
      properties:
        name:
          type: string
          description: The name of the object.
        labels:
          $ref: '#/components/schemas/Labels'
        annotations:
          $ref: '#/components/schemas/Annotations'
