# Copyright 2023 Robert Bosch GmbH
#
# SPDX-License-Identifier: Apache-2.0

---
openapi: 3.0.0
info:
  title: Model
  version: 0.0.1
paths:
  /Model:
    get:
      responses:
        '200':
          description: ''
components:
  schemas:
    Model:
      description: A model definition.
      type: object
      required:
        - kind
        - spec
      properties:
        kind:
          type: string
          enum:
            - Model
        metadata:
          $ref: 'metadata.yaml#/components/schemas/ObjectMetadata'
        spec:
          type: object
          properties:
            runtime:
              type: object
              description: Collection of runtimes made available by this model (package).
              properties:
                executable:
                  type: array
                  description: Executable runtime specifications.
                  items:
                    $ref: '#/components/schemas/RuntimeSpec'
                dynlib:
                  type: array
                  description: Dynamic Library runtime specifications.
                  items:
                    $ref: '#/components/schemas/RuntimeSpec'
                container:
                  type: array
                  description: Container runtime specifications.
                  items:
                    $ref: '#/components/schemas/RuntimeSpec'
                mcl:
                  type: array
                  description: Model Compatibility Library runtime specifications.
                  items:
                    $ref: '#/components/schemas/RuntimeSpec'
            channels:
              type: array
              description: A list of channels belonging to this model.
              items:
                $ref: 'channel.yaml#/components/schemas/Channel'
    RuntimeSpec:
      type: object
      description: A runtime definition.
      required:
        - path
      properties:
        path:
          type: string
          description: The relative (to the model package) path to the runtime artifact.
        os:
          type: string
          description: Indicate the operating system of the runtime (e.g. linux, windows).
        arch:
          type: string
          description: Indicate the architecture of the runtime (e.g. amd64, w32)
        variant:
          type: string
          description: Indicate the architecture sub variant of the runtime (e.g. v7)
        libs:
          type: array
          description: A list of libraries on which the runtime is dependant.
          items:
            type: string
        annotations:
          $ref: 'metadata.yaml#/components/schemas/Annotations'
