# Copyright 2023 Robert Bosch GmbH
#
# SPDX-License-Identifier: Apache-2.0

---
openapi: 3.0.0
info:
  title: Runnable
  version: 1.0.0
paths:
  /Runnable:
    get:
      responses:
        '200':
          description: ''
          content:
            text/yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Runnable'
components:
  schemas:
    Runnable:
      description: |
        A Runnable definition.

        ### Supported annotations:
        |Annotation|Description|
        |---|---|
        |`target_lib`|Relative path of the shared library containing the Runnable library.
      type: object
      required:
        - kind
        - spec
      properties:
        kind:
          type: string
          enum:
            - Runnable
        metadata:
          $ref: 'metadata.yaml#/components/schemas/ObjectMetadata'
        spec:
          $ref: '#/components/schemas/RunnableSpec'
      example:
        kind: Runnable
        metadata:
          name: target
          annotations:
            target_lib: examples/stub/lib/target.so
        spec:
          tasks:
            - function: task_init
              schedule: 0
            - function: task_5ms
              schedule: 5
            - function: task_10ms
              schedule: 10
            - function: task_20ms
              schedule: 20
            - function: task_40ms
              schedule: 40
    RunnableSpec:
      type: object
      required:
        - tasks
      properties:
        tasks:
          type: array
          description: A list of tasks belonging to this Runnable.
          items:
            $ref: '#/components/schemas/Task'
    Task:
      type: object
      description: |
        A Runnable task definition.
      required:
        - function
        - schedule
      properties:
        function:
          type: string
          description: |
            The name of the function representing the task. This function
            will be loaded from the library referenced by the Runnable
            annotation `target_lib`.
          example: task_init
        schedule:
          type: integer
          description: The task schedule interval (in milliseconds).
          example: 20