# Copyright 2023 Robert Bosch GmbH
#
# SPDX-License-Identifier: Apache-2.0

---
openapi: 3.0.0
info:
  title: SignalGroup
  version: 0.0.1
paths:
  /SignalGroup:
    get:
      responses:
        '200':
          description: ''
components:
  schemas:
    SignalGroup:
      description: A signal group definition.
      required:
        - kind
        - spec
      properties:
        kind:
          type: string
          enum:
            - SignalGroup
        metadata:
          $ref: 'metadata.yaml#/components/schemas/ObjectMetadata'
        spec:
          type: object
          required:
            - signals
          properties:
            signals:
              type: array
              description: A list of signals belonging to this signal group.
              items:
                $ref: '#/components/schemas/Signal'
    Signal:
      type: object
      description: A signal definition.
      required:
        - signal
      properties:
        signal:
          type: string
          description: The name of the signal.
        annotations:
          $ref: 'metadata.yaml#/components/schemas/Annotations'
