# Copyright 2023 Robert Bosch GmbH
#
# SPDX-License-Identifier: Apache-2.0

---
openapi: 3.0.0
info:
  title: Stack
  version: 0.0.1
paths:
  /Stack:
    get:
      responses:
        '200':
          description: ''
components:
  schemas:
    Stack:
      description: A stack definition.
      type: object
      required:
        - kind
        - spec
      properties:
        kind:
          type: string
          description: Indicate the type of object.
          enum:
            - Stack
        metadata:
          $ref: 'metadata.yaml#/components/schemas/ObjectMetadata'
        spec:
          type: object
          properties:
            connection:
              type: object
              properties:
                timeout:
                  type: string
                  description: Model timeout for messages from the transport.
                transport:
                  type: object
                  oneOf:
                    - type: object
                      required:
                        - redis
                      properties:
                        redis:
                          $ref: '#/components/schemas/RedisConnection'
                    - type: object
                      required:
                        - redispubsub
                      properties:
                        redispubsub:
                          $ref: '#/components/schemas/RedisConnection'
                    - type: object
                      required:
                        - mq
                      properties:
                        mq:
                          $ref: '#/components/schemas/MessageQueue'
            models:
              type: array
              items:
                $ref: '#/components/schemas/ModelInstance'
    ModelInstance:
      type: object
      description: A model instance object.
      required:
        - name
        - uid
        - model
      properties:
        name:
          type: string
        uid:
          type: integer
        annotations:
          $ref: 'metadata.yaml#/components/schemas/Annotations'
        model:
          type: object
          required:
            - name
          properties:
            name:
              type: string
            mcl:
              type: object
              required:
                - strategy
                - models
              properties:
                strategy:
                  type: string
                models:
                  type: array
                  description: A list of models belonging to this MCL.
                  items:
                    type: object
                    description: An MCL model definition.
                    required:
                      - name
                    properties:
                      name:
                        type: string
                        description: The name of the MCL model.
        channels:
          type: array
          items:
            $ref: 'channel.yaml#/components/schemas/Channel'
    RedisConnection:
      type: object
      description: Redis connection.
      properties:
        uri:
          type: string
        timeout:
          type: integer
    MessageQueue:
      type: object
      description: Message Queue based connection.
      properties:
        uri:
          type: string
