# Copyright 2024 Robert Bosch GmbH
#
# SPDX-License-Identifier: Apache-2.0

---
openapi: 3.0.0
info:
  title: Transform
paths:
  /Transform:
    get:
      responses:
        '200':
          description: ''
          content:
            text/yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transform'

components:
  schemas:
    Transform:
      type: object
      description: A transformation definition.
      example:
        linear:
          factor: 2.5
          offset: 1.0
        functions:
          vector:
            lua: |
              return function(s_vector)
                return s_vector * 10
              end
          model:
            lua: |
              return function(s_model)
                return s_model + 3
              end
      properties:
        linear:
          type: object
          description: >
            Represents a linear transformation in the form:
                $S_{\mathrm{model}} = S_{\mathrm{vector}} \cdot factor + offset$
          required:
            - factor
            - offset
          properties:
            factor:
              type: number
              format: double
            offset:
              type: number
              format: double
        functions:
          type: object
          description: >
            Represents a function transformation in the forms:
            - $S_{\mathrm{model}} = f(S_{\mathrm{vector}})$
              This function transform is applied _after_ all other transforms.
            - $S_{\mathrm{vector}} = f(S_{\mathrm{model}})$
              This function transform is applied _before_ all other transforms.
          properties:
            model:
              $ref: 'lua.yaml#/components/schemas/LuaFunction'
            vector:
              $ref: 'lua.yaml#/components/schemas/LuaFunction'
