# Copyright 2024 Robert Bosch GmbH
#
# SPDX-License-Identifier: Apache-2.0

---
openapi: 3.0.0
info:
  title: Transform
paths:
  /Transform:
    get:
      responses:
        '200':
          description: ''
          content:
            text/yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transform'
components:
  schemas:
    Transform:
      type: object
      description: A transformation definition.
      properties:
        linear:
          type: object
          description: >
            Represents a linear transformation in the form:
                f(X) = X * factor + offset.
          required:
            - factor
            - offset
          properties:
            factor:
              type: number
              format: double
            offset:
              type: number
              format: double
