// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import "strconv"

type FlexrayTransmitMode int8

const (
	FlexrayTransmitModeNone       FlexrayTransmitMode = 0
	FlexrayTransmitModeContinuous FlexrayTransmitMode = 1
	FlexrayTransmitModeSingleShot FlexrayTransmitMode = 2
)

var EnumNamesFlexrayTransmitMode = map[FlexrayTransmitMode]string{
	FlexrayTransmitModeNone:       "None",
	FlexrayTransmitModeContinuous: "Continuous",
	FlexrayTransmitModeSingleShot: "SingleShot",
}

var EnumValuesFlexrayTransmitMode = map[string]FlexrayTransmitMode{
	"None":       FlexrayTransmitModeNone,
	"Continuous": FlexrayTransmitModeContinuous,
	"SingleShot": FlexrayTransmitModeSingleShot,
}

func (v FlexrayTransmitMode) String() string {
	if s, ok := EnumNamesFlexrayTransmitMode[v]; ok {
		return s
	}
	return "FlexrayTransmitMode(" + strconv.FormatInt(int64(v), 10) + ")"
}
