// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FlexrayConfig struct {
	_tab flatbuffers.Table
}

func GetRootAsFlexrayConfig(buf []byte, offset flatbuffers.UOffsetT) *FlexrayConfig {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FlexrayConfig{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFlexrayConfig(buf []byte, offset flatbuffers.UOffsetT) *FlexrayConfig {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FlexrayConfig{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FlexrayConfig) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlexrayConfig) Table() flatbuffers.Table {
	return rcv._tab
}

/// Config: Node: Node configured Virtual Coldstart Nodes.
func (rcv *FlexrayConfig) Vcn(obj *FlexrayNodeIdentifier, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 8
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FlexrayConfig) VcnLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// Config: Node: Node configured Virtual Coldstart Nodes.
/// Config: Node: Initial FlexRay POC State for Channel A.
func (rcv *FlexrayConfig) InitialPocStateCha() FlexrayPocState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return FlexrayPocState(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Config: Node: Initial FlexRay POC State for Channel A.
func (rcv *FlexrayConfig) MutateInitialPocStateCha(n FlexrayPocState) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

/// Config: Node: Initial FlexRay POC State for Channel B.
func (rcv *FlexrayConfig) InitialPocStateChb() FlexrayPocState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return FlexrayPocState(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Config: Node: Initial FlexRay POC State for Channel B.
func (rcv *FlexrayConfig) MutateInitialPocStateChb(n FlexrayPocState) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

/// Config: Node: Inhibit NULL Frames.
func (rcv *FlexrayConfig) InhibitNullFrames() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

/// Config: Node: Inhibit NULL Frames.
func (rcv *FlexrayConfig) MutateInhibitNullFrames(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

/// Config: Controller: Macroticks per communication cycle (10..16000 MT).
func (rcv *FlexrayConfig) MacrotickPerCycle() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Controller: Macroticks per communication cycle (10..16000 MT).
func (rcv *FlexrayConfig) MutateMacrotickPerCycle(n uint16) bool {
	return rcv._tab.MutateUint16Slot(12, n)
}

/// Config: Controller: Microticks per communication cycle (640..640000 uT).
func (rcv *FlexrayConfig) MicrotickPerCycle() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Controller: Microticks per communication cycle (640..640000 uT).
func (rcv *FlexrayConfig) MutateMicrotickPerCycle(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

/// Config: Controller: Start of network idle, marks start-of-end of communication cycle (7..15997 MT).
func (rcv *FlexrayConfig) NetworkIdleStart() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Controller: Start of network idle, marks start-of-end of communication cycle (7..15997 MT).
func (rcv *FlexrayConfig) MutateNetworkIdleStart(n uint16) bool {
	return rcv._tab.MutateUint16Slot(16, n)
}

/// Config: Controller: Length of a static slot (4..659 MT).
func (rcv *FlexrayConfig) StaticSlotLength() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Controller: Length of a static slot (4..659 MT).
func (rcv *FlexrayConfig) MutateStaticSlotLength(n uint16) bool {
	return rcv._tab.MutateUint16Slot(18, n)
}

/// Config: Controller: Number of static slots (2..1023).
func (rcv *FlexrayConfig) StaticSlotCount() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Controller: Number of static slots (2..1023).
func (rcv *FlexrayConfig) MutateStaticSlotCount(n uint16) bool {
	return rcv._tab.MutateUint16Slot(20, n)
}

/// Config: Controller: Length of a mimi slot (2..63 MT).
func (rcv *FlexrayConfig) MinislotLength() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Controller: Length of a mimi slot (2..63 MT).
func (rcv *FlexrayConfig) MutateMinislotLength(n byte) bool {
	return rcv._tab.MutateByteSlot(22, n)
}

/// Config: Controller: Number of mini slots (0..7986).
func (rcv *FlexrayConfig) MinislotCount() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Controller: Number of mini slots (0..7986).
func (rcv *FlexrayConfig) MutateMinislotCount(n uint16) bool {
	return rcv._tab.MutateUint16Slot(24, n)
}

/// Config: Controller: Static segment payload length (0..254 bytes).
func (rcv *FlexrayConfig) StaticSlotPayloadLength() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Controller: Static segment payload length (0..254 bytes).
func (rcv *FlexrayConfig) MutateStaticSlotPayloadLength(n uint32) bool {
	return rcv._tab.MutateUint32Slot(26, n)
}

/// Config: Controller: The FlexRay bitrate.
func (rcv *FlexrayConfig) BitRate() FlexrayBitrate {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return FlexrayBitrate(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Config: Controller: The FlexRay bitrate.
func (rcv *FlexrayConfig) MutateBitRate(n FlexrayBitrate) bool {
	return rcv._tab.MutateInt8Slot(28, int8(n))
}

/// Config: Controller: Channels enabled.
func (rcv *FlexrayConfig) ChannelEnable() FlexrayChannel {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return FlexrayChannel(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Config: Controller: Channels enabled.
func (rcv *FlexrayConfig) MutateChannelEnable(n FlexrayChannel) bool {
	return rcv._tab.MutateInt8Slot(30, int8(n))
}

/// Config: Coldstart: Coldstart node (1=yes, 0=no).
func (rcv *FlexrayConfig) ColdstartNode() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

/// Config: Coldstart: Coldstart node (1=yes, 0=no).
func (rcv *FlexrayConfig) MutateColdstartNode(n bool) bool {
	return rcv._tab.MutateBoolSlot(32, n)
}

/// Config: Coldstart: Sync node (1=yes, 0=no).
func (rcv *FlexrayConfig) SyncNode() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

/// Config: Coldstart: Sync node (1=yes, 0=no).
func (rcv *FlexrayConfig) MutateSyncNode(n bool) bool {
	return rcv._tab.MutateBoolSlot(34, n)
}

/// Config: Coldstart: Coldstart attempts (2..31).
func (rcv *FlexrayConfig) ColdstartAttempts() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Coldstart: Coldstart attempts (2..31).
func (rcv *FlexrayConfig) MutateColdstartAttempts(n byte) bool {
	return rcv._tab.MutateByteSlot(36, n)
}

/// Config: Coldstart: Wakeup channel selector (0=A, 1=B).
func (rcv *FlexrayConfig) WakeupChannelSelect() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Coldstart: Wakeup channel selector (0=A, 1=B).
func (rcv *FlexrayConfig) MutateWakeupChannelSelect(n byte) bool {
	return rcv._tab.MutateByteSlot(38, n)
}

/// Config: Coldstart: Startup in single slot mode.
func (rcv *FlexrayConfig) SingleSlotEnabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

/// Config: Coldstart: Startup in single slot mode.
func (rcv *FlexrayConfig) MutateSingleSlotEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(40, n)
}

/// Config: Coldstart: Key slot id (for simplified startup).
func (rcv *FlexrayConfig) KeySlotId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Coldstart: Key slot id (for simplified startup).
func (rcv *FlexrayConfig) MutateKeySlotId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(42, n)
}

/// Config: Coldstart: Key slot Payload (related to LPDU).
func (rcv *FlexrayConfig) KeySlotPayload(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *FlexrayConfig) KeySlotPayloadLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FlexrayConfig) KeySlotPayloadBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Config: Coldstart: Key slot Payload (related to LPDU).
func (rcv *FlexrayConfig) MutateKeySlotPayload(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

/// Config: Coldstart: Key slot LPDU (for startup with payload).
func (rcv *FlexrayConfig) KeySlotLpdu(obj *FlexrayLpdu) *FlexrayLpdu {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(46))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FlexrayLpdu)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

/// Config: Coldstart: Key slot LPDU (for startup with payload).
/// Config: Frame: Frame/LPDU static config table.
func (rcv *FlexrayConfig) FrameTable(obj *FlexrayLpduConfig, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(48))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FlexrayConfig) FrameTableLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(48))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// Config: Frame: Frame/LPDU static config table.
/// Config: Frame: Config operation, relates specifically to 'frame_table'.
func (rcv *FlexrayConfig) ConfigOp() FlexrayConfigOp {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(50))
	if o != 0 {
		return FlexrayConfigOp(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Config: Frame: Config operation, relates specifically to 'frame_table'.
func (rcv *FlexrayConfig) MutateConfigOp(n FlexrayConfigOp) bool {
	return rcv._tab.MutateInt8Slot(50, int8(n))
}

/// Config: Node: Bus Model mode selector.
func (rcv *FlexrayConfig) BusModelMode() FlexrayBusModelMode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(52))
	if o != 0 {
		return FlexrayBusModelMode(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Config: Node: Bus Model mode selector.
func (rcv *FlexrayConfig) MutateBusModelMode(n FlexrayBusModelMode) bool {
	return rcv._tab.MutateInt8Slot(52, int8(n))
}

/// Config: Node: Node name (supports debug/logging).
func (rcv *FlexrayConfig) NodeName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(54))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Config: Node: Node name (supports debug/logging).
func FlexrayConfigStart(builder *flatbuffers.Builder) {
	builder.StartObject(26)
}
func FlexrayConfigAddVcn(builder *flatbuffers.Builder, vcn flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(vcn), 0)
}
func FlexrayConfigStartVcnVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 4)
}
func FlexrayConfigAddInitialPocStateCha(builder *flatbuffers.Builder, initialPocStateCha FlexrayPocState) {
	builder.PrependInt8Slot(1, int8(initialPocStateCha), 0)
}
func FlexrayConfigAddInitialPocStateChb(builder *flatbuffers.Builder, initialPocStateChb FlexrayPocState) {
	builder.PrependInt8Slot(2, int8(initialPocStateChb), 0)
}
func FlexrayConfigAddInhibitNullFrames(builder *flatbuffers.Builder, inhibitNullFrames bool) {
	builder.PrependBoolSlot(3, inhibitNullFrames, false)
}
func FlexrayConfigAddMacrotickPerCycle(builder *flatbuffers.Builder, macrotickPerCycle uint16) {
	builder.PrependUint16Slot(4, macrotickPerCycle, 0)
}
func FlexrayConfigAddMicrotickPerCycle(builder *flatbuffers.Builder, microtickPerCycle uint32) {
	builder.PrependUint32Slot(5, microtickPerCycle, 0)
}
func FlexrayConfigAddNetworkIdleStart(builder *flatbuffers.Builder, networkIdleStart uint16) {
	builder.PrependUint16Slot(6, networkIdleStart, 0)
}
func FlexrayConfigAddStaticSlotLength(builder *flatbuffers.Builder, staticSlotLength uint16) {
	builder.PrependUint16Slot(7, staticSlotLength, 0)
}
func FlexrayConfigAddStaticSlotCount(builder *flatbuffers.Builder, staticSlotCount uint16) {
	builder.PrependUint16Slot(8, staticSlotCount, 0)
}
func FlexrayConfigAddMinislotLength(builder *flatbuffers.Builder, minislotLength byte) {
	builder.PrependByteSlot(9, minislotLength, 0)
}
func FlexrayConfigAddMinislotCount(builder *flatbuffers.Builder, minislotCount uint16) {
	builder.PrependUint16Slot(10, minislotCount, 0)
}
func FlexrayConfigAddStaticSlotPayloadLength(builder *flatbuffers.Builder, staticSlotPayloadLength uint32) {
	builder.PrependUint32Slot(11, staticSlotPayloadLength, 0)
}
func FlexrayConfigAddBitRate(builder *flatbuffers.Builder, bitRate FlexrayBitrate) {
	builder.PrependInt8Slot(12, int8(bitRate), 0)
}
func FlexrayConfigAddChannelEnable(builder *flatbuffers.Builder, channelEnable FlexrayChannel) {
	builder.PrependInt8Slot(13, int8(channelEnable), 0)
}
func FlexrayConfigAddColdstartNode(builder *flatbuffers.Builder, coldstartNode bool) {
	builder.PrependBoolSlot(14, coldstartNode, false)
}
func FlexrayConfigAddSyncNode(builder *flatbuffers.Builder, syncNode bool) {
	builder.PrependBoolSlot(15, syncNode, false)
}
func FlexrayConfigAddColdstartAttempts(builder *flatbuffers.Builder, coldstartAttempts byte) {
	builder.PrependByteSlot(16, coldstartAttempts, 0)
}
func FlexrayConfigAddWakeupChannelSelect(builder *flatbuffers.Builder, wakeupChannelSelect byte) {
	builder.PrependByteSlot(17, wakeupChannelSelect, 0)
}
func FlexrayConfigAddSingleSlotEnabled(builder *flatbuffers.Builder, singleSlotEnabled bool) {
	builder.PrependBoolSlot(18, singleSlotEnabled, false)
}
func FlexrayConfigAddKeySlotId(builder *flatbuffers.Builder, keySlotId uint16) {
	builder.PrependUint16Slot(19, keySlotId, 0)
}
func FlexrayConfigAddKeySlotPayload(builder *flatbuffers.Builder, keySlotPayload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(20, flatbuffers.UOffsetT(keySlotPayload), 0)
}
func FlexrayConfigStartKeySlotPayloadVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func FlexrayConfigAddKeySlotLpdu(builder *flatbuffers.Builder, keySlotLpdu flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(21, flatbuffers.UOffsetT(keySlotLpdu), 0)
}
func FlexrayConfigAddFrameTable(builder *flatbuffers.Builder, frameTable flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(22, flatbuffers.UOffsetT(frameTable), 0)
}
func FlexrayConfigStartFrameTableVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FlexrayConfigAddConfigOp(builder *flatbuffers.Builder, configOp FlexrayConfigOp) {
	builder.PrependInt8Slot(23, int8(configOp), 0)
}
func FlexrayConfigAddBusModelMode(builder *flatbuffers.Builder, busModelMode FlexrayBusModelMode) {
	builder.PrependInt8Slot(24, int8(busModelMode), 0)
}
func FlexrayConfigAddNodeName(builder *flatbuffers.Builder, nodeName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(25, flatbuffers.UOffsetT(nodeName), 0)
}
func FlexrayConfigEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
