// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import "strconv"

type FlexrayChannel int8

const (
	FlexrayChannelNone FlexrayChannel = 0
	FlexrayChannelA    FlexrayChannel = 1
	FlexrayChannelB    FlexrayChannel = 2
	FlexrayChannelAB   FlexrayChannel = 3
)

var EnumNamesFlexrayChannel = map[FlexrayChannel]string{
	FlexrayChannelNone: "None",
	FlexrayChannelA:    "A",
	FlexrayChannelB:    "B",
	FlexrayChannelAB:   "AB",
}

var EnumValuesFlexrayChannel = map[string]FlexrayChannel{
	"None": FlexrayChannelNone,
	"A":    FlexrayChannelA,
	"B":    FlexrayChannelB,
	"AB":   FlexrayChannelAB,
}

func (v FlexrayChannel) String() string {
	if s, ok := EnumNamesFlexrayChannel[v]; ok {
		return s
	}
	return "FlexrayChannel(" + strconv.FormatInt(int64(v), 10) + ")"
}
