// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import "strconv"

type FlexrayBusModelMode int8

const (
	FlexrayBusModelModeNone FlexrayBusModelMode = 0
	FlexrayBusModelModePop  FlexrayBusModelMode = 1
)

var EnumNamesFlexrayBusModelMode = map[FlexrayBusModelMode]string{
	FlexrayBusModelModeNone: "None",
	FlexrayBusModelModePop:  "Pop",
}

var EnumValuesFlexrayBusModelMode = map[string]FlexrayBusModelMode{
	"None": FlexrayBusModelModeNone,
	"Pop":  FlexrayBusModelModePop,
}

func (v FlexrayBusModelMode) String() string {
	if s, ok := EnumNamesFlexrayBusModelMode[v]; ok {
		return s
	}
	return "FlexrayBusModelMode(" + strconv.FormatInt(int64(v), 10) + ")"
}
