// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FlexrayStatus struct {
	_tab flatbuffers.Table
}

func GetRootAsFlexrayStatus(buf []byte, offset flatbuffers.UOffsetT) *FlexrayStatus {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FlexrayStatus{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFlexrayStatus(buf []byte, offset flatbuffers.UOffsetT) *FlexrayStatus {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FlexrayStatus{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FlexrayStatus) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlexrayStatus) Table() flatbuffers.Table {
	return rcv._tab
}

/// Status: The macrotick (MT) associated with the containing PDU Stream Object.
func (rcv *FlexrayStatus) Macrotick() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Status: The macrotick (MT) associated with the containing PDU Stream Object.
func (rcv *FlexrayStatus) MutateMacrotick(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

/// Status: The cycle count associated with the containing PDU Stream Object.
func (rcv *FlexrayStatus) Cycle() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

/// Status: The cycle count associated with the containing PDU Stream Object.
func (rcv *FlexrayStatus) MutateCycle(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *FlexrayStatus) Reserved() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FlexrayStatus) MutateReserved(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

/// Status: Channel A: Transceiver State.
func (rcv *FlexrayStatus) TcvrStateCha() FlexrayTransceiverState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return FlexrayTransceiverState(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Status: Channel A: Transceiver State.
func (rcv *FlexrayStatus) MutateTcvrStateCha(n FlexrayTransceiverState) bool {
	return rcv._tab.MutateInt8Slot(10, int8(n))
}

/// Status: Channel B: Transceiver State.
func (rcv *FlexrayStatus) TcvrStateChb() FlexrayTransceiverState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return FlexrayTransceiverState(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Status: Channel B: Transceiver State.
func (rcv *FlexrayStatus) MutateTcvrStateChb(n FlexrayTransceiverState) bool {
	return rcv._tab.MutateInt8Slot(12, int8(n))
}

/// Status: Channel A: State of the FlexRay POC.
func (rcv *FlexrayStatus) PocStateCha() FlexrayPocState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return FlexrayPocState(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Status: Channel A: State of the FlexRay POC.
func (rcv *FlexrayStatus) MutatePocStateCha(n FlexrayPocState) bool {
	return rcv._tab.MutateInt8Slot(14, int8(n))
}

/// Status: Channel B: State of the FlexRay POC.
func (rcv *FlexrayStatus) PocStateChb() FlexrayPocState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return FlexrayPocState(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Status: Channel B: State of the FlexRay POC.
func (rcv *FlexrayStatus) MutatePocStateChb(n FlexrayPocState) bool {
	return rcv._tab.MutateInt8Slot(16, int8(n))
}

/// Status: Channel A: A POC command.
func (rcv *FlexrayStatus) PocCommandCha() FlexrayPocCommand {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return FlexrayPocCommand(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Status: Channel A: A POC command.
func (rcv *FlexrayStatus) MutatePocCommandCha(n FlexrayPocCommand) bool {
	return rcv._tab.MutateInt8Slot(18, int8(n))
}

/// Status: Channel B: A POC command.
func (rcv *FlexrayStatus) PocCommandChb() FlexrayPocCommand {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return FlexrayPocCommand(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Status: Channel B: A POC command.
func (rcv *FlexrayStatus) MutatePocCommandChb(n FlexrayPocCommand) bool {
	return rcv._tab.MutateInt8Slot(20, int8(n))
}

func FlexrayStatusStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func FlexrayStatusAddMacrotick(builder *flatbuffers.Builder, macrotick uint16) {
	builder.PrependUint16Slot(0, macrotick, 0)
}
func FlexrayStatusAddCycle(builder *flatbuffers.Builder, cycle byte) {
	builder.PrependByteSlot(1, cycle, 0)
}
func FlexrayStatusAddReserved(builder *flatbuffers.Builder, reserved uint16) {
	builder.PrependUint16Slot(2, reserved, 0)
}
func FlexrayStatusAddTcvrStateCha(builder *flatbuffers.Builder, tcvrStateCha FlexrayTransceiverState) {
	builder.PrependInt8Slot(3, int8(tcvrStateCha), 0)
}
func FlexrayStatusAddTcvrStateChb(builder *flatbuffers.Builder, tcvrStateChb FlexrayTransceiverState) {
	builder.PrependInt8Slot(4, int8(tcvrStateChb), 0)
}
func FlexrayStatusAddPocStateCha(builder *flatbuffers.Builder, pocStateCha FlexrayPocState) {
	builder.PrependInt8Slot(5, int8(pocStateCha), 0)
}
func FlexrayStatusAddPocStateChb(builder *flatbuffers.Builder, pocStateChb FlexrayPocState) {
	builder.PrependInt8Slot(6, int8(pocStateChb), 0)
}
func FlexrayStatusAddPocCommandCha(builder *flatbuffers.Builder, pocCommandCha FlexrayPocCommand) {
	builder.PrependInt8Slot(7, int8(pocCommandCha), 0)
}
func FlexrayStatusAddPocCommandChb(builder *flatbuffers.Builder, pocCommandChb FlexrayPocCommand) {
	builder.PrependInt8Slot(8, int8(pocCommandChb), 0)
}
func FlexrayStatusEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
