// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import "strconv"

type FlexrayChannelStatus int8

const (
	FlexrayChannelStatusA FlexrayChannelStatus = 0
	FlexrayChannelStatusB FlexrayChannelStatus = 1
)

var EnumNamesFlexrayChannelStatus = map[FlexrayChannelStatus]string{
	FlexrayChannelStatusA: "A",
	FlexrayChannelStatusB: "B",
}

var EnumValuesFlexrayChannelStatus = map[string]FlexrayChannelStatus{
	"A": FlexrayChannelStatusA,
	"B": FlexrayChannelStatusB,
}

func (v FlexrayChannelStatus) String() string {
	if s, ok := EnumNamesFlexrayChannelStatus[v]; ok {
		return s
	}
	return "FlexrayChannelStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
