// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FlexrayNodeIdentifier struct {
	_tab flatbuffers.Struct
}

func (rcv *FlexrayNodeIdentifier) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlexrayNodeIdentifier) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *FlexrayNodeIdentifier) EcuId() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *FlexrayNodeIdentifier) MutateEcuId(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *FlexrayNodeIdentifier) CcId() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *FlexrayNodeIdentifier) MutateCcId(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *FlexrayNodeIdentifier) SwcId() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *FlexrayNodeIdentifier) MutateSwcId(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateFlexrayNodeIdentifier(builder *flatbuffers.Builder, ecuId uint16, ccId uint16, swcId uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependUint32(swcId)
	builder.PrependUint16(ccId)
	builder.PrependUint16(ecuId)
	return builder.Offset()
}
