// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import "strconv"

type FlexrayMetadataType byte

const (
	FlexrayMetadataTypeNONE   FlexrayMetadataType = 0
	FlexrayMetadataTypeLpdu   FlexrayMetadataType = 1
	FlexrayMetadataTypeConfig FlexrayMetadataType = 2
	FlexrayMetadataTypeStatus FlexrayMetadataType = 3
)

var EnumNamesFlexrayMetadataType = map[FlexrayMetadataType]string{
	FlexrayMetadataTypeNONE:   "NONE",
	FlexrayMetadataTypeLpdu:   "Lpdu",
	FlexrayMetadataTypeConfig: "Config",
	FlexrayMetadataTypeStatus: "Status",
}

var EnumValuesFlexrayMetadataType = map[string]FlexrayMetadataType{
	"NONE":   FlexrayMetadataTypeNONE,
	"Lpdu":   FlexrayMetadataTypeLpdu,
	"Config": FlexrayMetadataTypeConfig,
	"Status": FlexrayMetadataTypeStatus,
}

func (v FlexrayMetadataType) String() string {
	if s, ok := EnumNamesFlexrayMetadataType[v]; ok {
		return s
	}
	return "FlexrayMetadataType(" + strconv.FormatInt(int64(v), 10) + ")"
}
