// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import "strconv"

type FlexrayTransceiverState int8

const (
	FlexrayTransceiverStateNone         FlexrayTransceiverState = 0
	FlexrayTransceiverStateNoPower      FlexrayTransceiverState = 1
	FlexrayTransceiverStateNoConnection FlexrayTransceiverState = 2
	FlexrayTransceiverStateNoSignal     FlexrayTransceiverState = 3
	FlexrayTransceiverStateCAS          FlexrayTransceiverState = 4
	FlexrayTransceiverStateWUP          FlexrayTransceiverState = 5
	FlexrayTransceiverStateFrameSync    FlexrayTransceiverState = 6
	FlexrayTransceiverStateFrameError   FlexrayTransceiverState = 7
)

var EnumNamesFlexrayTransceiverState = map[FlexrayTransceiverState]string{
	FlexrayTransceiverStateNone:         "None",
	FlexrayTransceiverStateNoPower:      "NoPower",
	FlexrayTransceiverStateNoConnection: "NoConnection",
	FlexrayTransceiverStateNoSignal:     "NoSignal",
	FlexrayTransceiverStateCAS:          "CAS",
	FlexrayTransceiverStateWUP:          "WUP",
	FlexrayTransceiverStateFrameSync:    "FrameSync",
	FlexrayTransceiverStateFrameError:   "FrameError",
}

var EnumValuesFlexrayTransceiverState = map[string]FlexrayTransceiverState{
	"None":         FlexrayTransceiverStateNone,
	"NoPower":      FlexrayTransceiverStateNoPower,
	"NoConnection": FlexrayTransceiverStateNoConnection,
	"NoSignal":     FlexrayTransceiverStateNoSignal,
	"CAS":          FlexrayTransceiverStateCAS,
	"WUP":          FlexrayTransceiverStateWUP,
	"FrameSync":    FlexrayTransceiverStateFrameSync,
	"FrameError":   FlexrayTransceiverStateFrameError,
}

func (v FlexrayTransceiverState) String() string {
	if s, ok := EnumNamesFlexrayTransceiverState[v]; ok {
		return s
	}
	return "FlexrayTransceiverState(" + strconv.FormatInt(int64(v), 10) + ")"
}
