// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import "strconv"

type FlexrayDirection int8

const (
	FlexrayDirectionNone FlexrayDirection = 0
	FlexrayDirectionRx   FlexrayDirection = 1
	FlexrayDirectionTx   FlexrayDirection = 2
)

var EnumNamesFlexrayDirection = map[FlexrayDirection]string{
	FlexrayDirectionNone: "None",
	FlexrayDirectionRx:   "Rx",
	FlexrayDirectionTx:   "Tx",
}

var EnumValuesFlexrayDirection = map[string]FlexrayDirection{
	"None": FlexrayDirectionNone,
	"Rx":   FlexrayDirectionRx,
	"Tx":   FlexrayDirectionTx,
}

func (v FlexrayDirection) String() string {
	if s, ok := EnumNamesFlexrayDirection[v]; ok {
		return s
	}
	return "FlexrayDirection(" + strconv.FormatInt(int64(v), 10) + ")"
}
