// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import "strconv"

type FlexrayConfigOp int8

const (
	FlexrayConfigOpSet              FlexrayConfigOp = 0
	FlexrayConfigOpFrameTableSet    FlexrayConfigOp = 1
	FlexrayConfigOpFrameTableMerge  FlexrayConfigOp = 2
	FlexrayConfigOpFrameTableDelete FlexrayConfigOp = 3
)

var EnumNamesFlexrayConfigOp = map[FlexrayConfigOp]string{
	FlexrayConfigOpSet:              "Set",
	FlexrayConfigOpFrameTableSet:    "FrameTableSet",
	FlexrayConfigOpFrameTableMerge:  "FrameTableMerge",
	FlexrayConfigOpFrameTableDelete: "FrameTableDelete",
}

var EnumValuesFlexrayConfigOp = map[string]FlexrayConfigOp{
	"Set":              FlexrayConfigOpSet,
	"FrameTableSet":    FlexrayConfigOpFrameTableSet,
	"FrameTableMerge":  FlexrayConfigOpFrameTableMerge,
	"FrameTableDelete": FlexrayConfigOpFrameTableDelete,
}

func (v FlexrayConfigOp) String() string {
	if s, ok := EnumNamesFlexrayConfigOp[v]; ok {
		return s
	}
	return "FlexrayConfigOp(" + strconv.FormatInt(int64(v), 10) + ")"
}
