// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import "strconv"

type FlexrayLpduStatus int8

const (
	FlexrayLpduStatusNone           FlexrayLpduStatus = 0
	FlexrayLpduStatusTransmitted    FlexrayLpduStatus = 1
	FlexrayLpduStatusNotTransmitted FlexrayLpduStatus = 2
	FlexrayLpduStatusReceived       FlexrayLpduStatus = 3
	FlexrayLpduStatusNotReceived    FlexrayLpduStatus = 4
)

var EnumNamesFlexrayLpduStatus = map[FlexrayLpduStatus]string{
	FlexrayLpduStatusNone:           "None",
	FlexrayLpduStatusTransmitted:    "Transmitted",
	FlexrayLpduStatusNotTransmitted: "NotTransmitted",
	FlexrayLpduStatusReceived:       "Received",
	FlexrayLpduStatusNotReceived:    "NotReceived",
}

var EnumValuesFlexrayLpduStatus = map[string]FlexrayLpduStatus{
	"None":           FlexrayLpduStatusNone,
	"Transmitted":    FlexrayLpduStatusTransmitted,
	"NotTransmitted": FlexrayLpduStatusNotTransmitted,
	"Received":       FlexrayLpduStatusReceived,
	"NotReceived":    FlexrayLpduStatusNotReceived,
}

func (v FlexrayLpduStatus) String() string {
	if s, ok := EnumNamesFlexrayLpduStatus[v]; ok {
		return s
	}
	return "FlexrayLpduStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
