// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FlexrayMetadata struct {
	_tab flatbuffers.Table
}

func GetRootAsFlexrayMetadata(buf []byte, offset flatbuffers.UOffsetT) *FlexrayMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FlexrayMetadata{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFlexrayMetadata(buf []byte, offset flatbuffers.UOffsetT) *FlexrayMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FlexrayMetadata{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FlexrayMetadata) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlexrayMetadata) Table() flatbuffers.Table {
	return rcv._tab
}

/// FlexRay Metadata: Node identifier of the _sending_ node.
func (rcv *FlexrayMetadata) NodeIdent(obj *FlexrayNodeIdentifier) *FlexrayNodeIdentifier {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(FlexrayNodeIdentifier)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

/// FlexRay Metadata: Node identifier of the _sending_ node.
func (rcv *FlexrayMetadata) MetadataType() FlexrayMetadataType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return FlexrayMetadataType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *FlexrayMetadata) MutateMetadataType(n FlexrayMetadataType) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

/// FlexRay Metadata: Metadata table.
func (rcv *FlexrayMetadata) Metadata(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

/// FlexRay Metadata: Metadata table.
/// FlexRay Metadata: PoP Node identifier of the node this message represents.
///     PoP:node_ident(0.0.0) sends message to node by setting pop_node_ident(1.0.0)
///     PoP Bus Model exchanges: node_ident <= pop_node_ident
func (rcv *FlexrayMetadata) PopNodeIdent(obj *FlexrayNodeIdentifier) *FlexrayNodeIdentifier {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(FlexrayNodeIdentifier)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

/// FlexRay Metadata: PoP Node identifier of the node this message represents.
///     PoP:node_ident(0.0.0) sends message to node by setting pop_node_ident(1.0.0)
///     PoP Bus Model exchanges: node_ident <= pop_node_ident
func FlexrayMetadataStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func FlexrayMetadataAddNodeIdent(builder *flatbuffers.Builder, nodeIdent flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(nodeIdent), 0)
}
func FlexrayMetadataAddMetadataType(builder *flatbuffers.Builder, metadataType FlexrayMetadataType) {
	builder.PrependByteSlot(1, byte(metadataType), 0)
}
func FlexrayMetadataAddMetadata(builder *flatbuffers.Builder, metadata flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(metadata), 0)
}
func FlexrayMetadataAddPopNodeIdent(builder *flatbuffers.Builder, popNodeIdent flatbuffers.UOffsetT) {
	builder.PrependStructSlot(3, flatbuffers.UOffsetT(popNodeIdent), 0)
}
func FlexrayMetadataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
