// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FlexrayLpduConfig struct {
	_tab flatbuffers.Table
}

func GetRootAsFlexrayLpduConfig(buf []byte, offset flatbuffers.UOffsetT) *FlexrayLpduConfig {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FlexrayLpduConfig{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFlexrayLpduConfig(buf []byte, offset flatbuffers.UOffsetT) *FlexrayLpduConfig {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FlexrayLpduConfig{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FlexrayLpduConfig) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlexrayLpduConfig) Table() flatbuffers.Table {
	return rcv._tab
}

/// Config: Slot ID of the frame.
func (rcv *FlexrayLpduConfig) SlotId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Slot ID of the frame.
func (rcv *FlexrayLpduConfig) MutateSlotId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

/// Config: Payload length.
func (rcv *FlexrayLpduConfig) PayloadLength() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Payload length.
func (rcv *FlexrayLpduConfig) MutatePayloadLength(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

/// Config: Number of cycles between frame transmission.
func (rcv *FlexrayLpduConfig) CycleRepetition() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Number of cycles between frame transmission.
func (rcv *FlexrayLpduConfig) MutateCycleRepetition(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

/// Config: Cycle when frame is first sent.
func (rcv *FlexrayLpduConfig) BaseCycle() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Cycle when frame is first sent.
func (rcv *FlexrayLpduConfig) MutateBaseCycle(n byte) bool {
	return rcv._tab.MutateByteSlot(10, n)
}

/// Config: Index into the FlexrayConfig.frame_table (self reference).
func (rcv *FlexrayLpduConfig) FrameTableIndex() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: Index into the FlexrayConfig.frame_table (self reference).
func (rcv *FlexrayLpduConfig) MutateFrameTableIndex(n uint16) bool {
	return rcv._tab.MutateUint16Slot(12, n)
}

/// Config: FlexRay controller/interface internal reference.
func (rcv *FlexrayLpduConfig) LpduTableIndex() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Config: FlexRay controller/interface internal reference.
func (rcv *FlexrayLpduConfig) MutateLpduTableIndex(n uint16) bool {
	return rcv._tab.MutateUint16Slot(14, n)
}

/// Config: Frame direction.
func (rcv *FlexrayLpduConfig) Direction() FlexrayDirection {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return FlexrayDirection(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Config: Frame direction.
func (rcv *FlexrayLpduConfig) MutateDirection(n FlexrayDirection) bool {
	return rcv._tab.MutateInt8Slot(16, int8(n))
}

/// Config: Channels the frame will be sent over.
func (rcv *FlexrayLpduConfig) Channel() FlexrayChannel {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return FlexrayChannel(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Config: Channels the frame will be sent over.
func (rcv *FlexrayLpduConfig) MutateChannel(n FlexrayChannel) bool {
	return rcv._tab.MutateInt8Slot(18, int8(n))
}

/// Config: Transmit mode of the frame.
func (rcv *FlexrayLpduConfig) TransmitMode() FlexrayTransmitMode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return FlexrayTransmitMode(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Config: Transmit mode of the frame.
func (rcv *FlexrayLpduConfig) MutateTransmitMode(n FlexrayTransmitMode) bool {
	return rcv._tab.MutateInt8Slot(20, int8(n))
}

/// Config: Status of this frame (actual/observed status).
func (rcv *FlexrayLpduConfig) Status() FlexrayLpduStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return FlexrayLpduStatus(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Config: Status of this frame (actual/observed status).
func (rcv *FlexrayLpduConfig) MutateStatus(n FlexrayLpduStatus) bool {
	return rcv._tab.MutateInt8Slot(22, int8(n))
}

/// Config: Inhibit NULL (null frames not indicated to Rx nodes).
func (rcv *FlexrayLpduConfig) InhibitNull() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

/// Config: Inhibit NULL (null frames not indicated to Rx nodes).
func (rcv *FlexrayLpduConfig) MutateInhibitNull(n bool) bool {
	return rcv._tab.MutateBoolSlot(24, n)
}

func FlexrayLpduConfigStart(builder *flatbuffers.Builder) {
	builder.StartObject(11)
}
func FlexrayLpduConfigAddSlotId(builder *flatbuffers.Builder, slotId uint16) {
	builder.PrependUint16Slot(0, slotId, 0)
}
func FlexrayLpduConfigAddPayloadLength(builder *flatbuffers.Builder, payloadLength byte) {
	builder.PrependByteSlot(1, payloadLength, 0)
}
func FlexrayLpduConfigAddCycleRepetition(builder *flatbuffers.Builder, cycleRepetition byte) {
	builder.PrependByteSlot(2, cycleRepetition, 0)
}
func FlexrayLpduConfigAddBaseCycle(builder *flatbuffers.Builder, baseCycle byte) {
	builder.PrependByteSlot(3, baseCycle, 0)
}
func FlexrayLpduConfigAddFrameTableIndex(builder *flatbuffers.Builder, frameTableIndex uint16) {
	builder.PrependUint16Slot(4, frameTableIndex, 0)
}
func FlexrayLpduConfigAddLpduTableIndex(builder *flatbuffers.Builder, lpduTableIndex uint16) {
	builder.PrependUint16Slot(5, lpduTableIndex, 0)
}
func FlexrayLpduConfigAddDirection(builder *flatbuffers.Builder, direction FlexrayDirection) {
	builder.PrependInt8Slot(6, int8(direction), 0)
}
func FlexrayLpduConfigAddChannel(builder *flatbuffers.Builder, channel FlexrayChannel) {
	builder.PrependInt8Slot(7, int8(channel), 0)
}
func FlexrayLpduConfigAddTransmitMode(builder *flatbuffers.Builder, transmitMode FlexrayTransmitMode) {
	builder.PrependInt8Slot(8, int8(transmitMode), 0)
}
func FlexrayLpduConfigAddStatus(builder *flatbuffers.Builder, status FlexrayLpduStatus) {
	builder.PrependInt8Slot(9, int8(status), 0)
}
func FlexrayLpduConfigAddInhibitNull(builder *flatbuffers.Builder, inhibitNull bool) {
	builder.PrependBoolSlot(10, inhibitNull, false)
}
func FlexrayLpduConfigEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
