// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import "strconv"

type FlexrayBitrate int8

const (
	FlexrayBitrateNone      FlexrayBitrate = 0
	FlexrayBitrateBR10Mbps  FlexrayBitrate = 1
	FlexrayBitrateBR5Mbps   FlexrayBitrate = 2
	FlexrayBitrateBR2_5Mbps FlexrayBitrate = 3
)

var EnumNamesFlexrayBitrate = map[FlexrayBitrate]string{
	FlexrayBitrateNone:      "None",
	FlexrayBitrateBR10Mbps:  "BR10Mbps",
	FlexrayBitrateBR5Mbps:   "BR5Mbps",
	FlexrayBitrateBR2_5Mbps: "BR2_5Mbps",
}

var EnumValuesFlexrayBitrate = map[string]FlexrayBitrate{
	"None":      FlexrayBitrateNone,
	"BR10Mbps":  FlexrayBitrateBR10Mbps,
	"BR5Mbps":   FlexrayBitrateBR5Mbps,
	"BR2_5Mbps": FlexrayBitrateBR2_5Mbps,
}

func (v FlexrayBitrate) String() string {
	if s, ok := EnumNamesFlexrayBitrate[v]; ok {
		return s
	}
	return "FlexrayBitrate(" + strconv.FormatInt(int64(v), 10) + ")"
}
