// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import "strconv"

type FlexrayPocCommand int8

const (
	FlexrayPocCommandNone      FlexrayPocCommand = 0
	FlexrayPocCommandConfig    FlexrayPocCommand = 1
	FlexrayPocCommandReady     FlexrayPocCommand = 2
	FlexrayPocCommandWakeup    FlexrayPocCommand = 3
	FlexrayPocCommandRun       FlexrayPocCommand = 4
	FlexrayPocCommandAllSlots  FlexrayPocCommand = 5
	FlexrayPocCommandHalt      FlexrayPocCommand = 6
	FlexrayPocCommandFreeze    FlexrayPocCommand = 7
	FlexrayPocCommandColdstart FlexrayPocCommand = 8
	FlexrayPocCommandNop       FlexrayPocCommand = 9
)

var EnumNamesFlexrayPocCommand = map[FlexrayPocCommand]string{
	FlexrayPocCommandNone:      "None",
	FlexrayPocCommandConfig:    "Config",
	FlexrayPocCommandReady:     "Ready",
	FlexrayPocCommandWakeup:    "Wakeup",
	FlexrayPocCommandRun:       "Run",
	FlexrayPocCommandAllSlots:  "AllSlots",
	FlexrayPocCommandHalt:      "Halt",
	FlexrayPocCommandFreeze:    "Freeze",
	FlexrayPocCommandColdstart: "Coldstart",
	FlexrayPocCommandNop:       "Nop",
}

var EnumValuesFlexrayPocCommand = map[string]FlexrayPocCommand{
	"None":      FlexrayPocCommandNone,
	"Config":    FlexrayPocCommandConfig,
	"Ready":     FlexrayPocCommandReady,
	"Wakeup":    FlexrayPocCommandWakeup,
	"Run":       FlexrayPocCommandRun,
	"AllSlots":  FlexrayPocCommandAllSlots,
	"Halt":      FlexrayPocCommandHalt,
	"Freeze":    FlexrayPocCommandFreeze,
	"Coldstart": FlexrayPocCommandColdstart,
	"Nop":       FlexrayPocCommandNop,
}

func (v FlexrayPocCommand) String() string {
	if s, ok := EnumNamesFlexrayPocCommand[v]; ok {
		return s
	}
	return "FlexrayPocCommand(" + strconv.FormatInt(int64(v), 10) + ")"
}
