// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import "strconv"

type FlexrayPocState int8

const (
	FlexrayPocStateDefaultConfig FlexrayPocState = 0
	FlexrayPocStateConfig        FlexrayPocState = 1
	FlexrayPocStateReady         FlexrayPocState = 2
	FlexrayPocStateWakeup        FlexrayPocState = 3
	FlexrayPocStateStartup       FlexrayPocState = 4
	FlexrayPocStateNormalActive  FlexrayPocState = 5
	FlexrayPocStateNormalPassive FlexrayPocState = 6
	FlexrayPocStateStateHalt     FlexrayPocState = 7
	FlexrayPocStateFreeze        FlexrayPocState = 8
	FlexrayPocStateUndefined     FlexrayPocState = 9
)

var EnumNamesFlexrayPocState = map[FlexrayPocState]string{
	FlexrayPocStateDefaultConfig: "DefaultConfig",
	FlexrayPocStateConfig:        "Config",
	FlexrayPocStateReady:         "Ready",
	FlexrayPocStateWakeup:        "Wakeup",
	FlexrayPocStateStartup:       "Startup",
	FlexrayPocStateNormalActive:  "NormalActive",
	FlexrayPocStateNormalPassive: "NormalPassive",
	FlexrayPocStateStateHalt:     "StateHalt",
	FlexrayPocStateFreeze:        "Freeze",
	FlexrayPocStateUndefined:     "Undefined",
}

var EnumValuesFlexrayPocState = map[string]FlexrayPocState{
	"DefaultConfig": FlexrayPocStateDefaultConfig,
	"Config":        FlexrayPocStateConfig,
	"Ready":         FlexrayPocStateReady,
	"Wakeup":        FlexrayPocStateWakeup,
	"Startup":       FlexrayPocStateStartup,
	"NormalActive":  FlexrayPocStateNormalActive,
	"NormalPassive": FlexrayPocStateNormalPassive,
	"StateHalt":     FlexrayPocStateStateHalt,
	"Freeze":        FlexrayPocStateFreeze,
	"Undefined":     FlexrayPocStateUndefined,
}

func (v FlexrayPocState) String() string {
	if s, ok := EnumNamesFlexrayPocState[v]; ok {
		return s
	}
	return "FlexrayPocState(" + strconv.FormatInt(int64(v), 10) + ")"
}
