// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FlexrayLpdu struct {
	_tab flatbuffers.Table
}

func GetRootAsFlexrayLpdu(buf []byte, offset flatbuffers.UOffsetT) *FlexrayLpdu {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FlexrayLpdu{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFlexrayLpdu(buf []byte, offset flatbuffers.UOffsetT) *FlexrayLpdu {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FlexrayLpdu{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FlexrayLpdu) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlexrayLpdu) Table() flatbuffers.Table {
	return rcv._tab
}

/// Frame: Cycle the frame was received on.
func (rcv *FlexrayLpdu) Cycle() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

/// Frame: Cycle the frame was received on.
func (rcv *FlexrayLpdu) MutateCycle(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

/// Frame: Index into Frame Config table.
func (rcv *FlexrayLpdu) FrameConfigIndex() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Frame: Index into Frame Config table.
func (rcv *FlexrayLpdu) MutateFrameConfigIndex(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

/// Frame: The frame header has the 'Null Frame' indicator set.
func (rcv *FlexrayLpdu) NullFrame() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

/// Frame: The frame header has the 'Null Frame' indicator set.
func (rcv *FlexrayLpdu) MutateNullFrame(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

/// Frame: The frame header has the 'Null Frame' indicator set.
func (rcv *FlexrayLpdu) SyncFrame() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

/// Frame: The frame header has the 'Null Frame' indicator set.
func (rcv *FlexrayLpdu) MutateSyncFrame(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

/// Frame: The frame header has the 'Null Frame' indicator set.
func (rcv *FlexrayLpdu) StartupFrame() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

/// Frame: The frame header has the 'Null Frame' indicator set.
func (rcv *FlexrayLpdu) MutateStartupFrame(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

/// Frame: The frame header has the 'Null Frame' indicator set.
func (rcv *FlexrayLpdu) PayloadPreamble() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

/// Frame: The frame header has the 'Null Frame' indicator set.
func (rcv *FlexrayLpdu) MutatePayloadPreamble(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

/// Frame: Status of this frame (actual/observed status).
func (rcv *FlexrayLpdu) Status() FlexrayLpduStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return FlexrayLpduStatus(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Frame: Status of this frame (actual/observed status).
func (rcv *FlexrayLpdu) MutateStatus(n FlexrayLpduStatus) bool {
	return rcv._tab.MutateInt8Slot(16, int8(n))
}

/// Frame: Macrotick the frame was received on (testing/internal use only).
func (rcv *FlexrayLpdu) Macrotick() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Frame: Macrotick the frame was received on (testing/internal use only).
func (rcv *FlexrayLpdu) MutateMacrotick(n uint16) bool {
	return rcv._tab.MutateUint16Slot(18, n)
}

func FlexrayLpduStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func FlexrayLpduAddCycle(builder *flatbuffers.Builder, cycle byte) {
	builder.PrependByteSlot(0, cycle, 0)
}
func FlexrayLpduAddFrameConfigIndex(builder *flatbuffers.Builder, frameConfigIndex uint16) {
	builder.PrependUint16Slot(1, frameConfigIndex, 0)
}
func FlexrayLpduAddNullFrame(builder *flatbuffers.Builder, nullFrame bool) {
	builder.PrependBoolSlot(2, nullFrame, false)
}
func FlexrayLpduAddSyncFrame(builder *flatbuffers.Builder, syncFrame bool) {
	builder.PrependBoolSlot(3, syncFrame, false)
}
func FlexrayLpduAddStartupFrame(builder *flatbuffers.Builder, startupFrame bool) {
	builder.PrependBoolSlot(4, startupFrame, false)
}
func FlexrayLpduAddPayloadPreamble(builder *flatbuffers.Builder, payloadPreamble bool) {
	builder.PrependBoolSlot(5, payloadPreamble, false)
}
func FlexrayLpduAddStatus(builder *flatbuffers.Builder, status FlexrayLpduStatus) {
	builder.PrependInt8Slot(6, int8(status), 0)
}
func FlexrayLpduAddMacrotick(builder *flatbuffers.Builder, macrotick uint16) {
	builder.PrependUint16Slot(7, macrotick, 0)
}
func FlexrayLpduEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
