// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pdu

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StructMetadata struct {
	_tab flatbuffers.Table
}

func GetRootAsStructMetadata(buf []byte, offset flatbuffers.UOffsetT) *StructMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StructMetadata{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStructMetadata(buf []byte, offset flatbuffers.UOffsetT) *StructMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StructMetadata{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *StructMetadata) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StructMetadata) Table() flatbuffers.Table {
	return rcv._tab
}

/// Struct: Name of the struct type.
func (rcv *StructMetadata) TypeName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Struct: Name of the struct type.
/// Struct: Name of the struct instance/variable.
func (rcv *StructMetadata) VarName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Struct: Name of the struct instance/variable.
/// Struct: Encoding used to package the struct instance/variable (default is 'memcpy').
func (rcv *StructMetadata) Encoding() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Struct: Encoding used to package the struct instance/variable (default is 'memcpy').
func (rcv *StructMetadata) AttributeAligned() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StructMetadata) MutateAttributeAligned(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func (rcv *StructMetadata) AttributePacked() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StructMetadata) MutateAttributePacked(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *StructMetadata) PlatformArch() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StructMetadata) PlatformOs() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StructMetadata) PlatformAbi() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StructMetadataStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func StructMetadataAddTypeName(builder *flatbuffers.Builder, typeName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(typeName), 0)
}
func StructMetadataAddVarName(builder *flatbuffers.Builder, varName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(varName), 0)
}
func StructMetadataAddEncoding(builder *flatbuffers.Builder, encoding flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(encoding), 0)
}
func StructMetadataAddAttributeAligned(builder *flatbuffers.Builder, attributeAligned uint16) {
	builder.PrependUint16Slot(3, attributeAligned, 0)
}
func StructMetadataAddAttributePacked(builder *flatbuffers.Builder, attributePacked bool) {
	builder.PrependBoolSlot(4, attributePacked, false)
}
func StructMetadataAddPlatformArch(builder *flatbuffers.Builder, platformArch flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(platformArch), 0)
}
func StructMetadataAddPlatformOs(builder *flatbuffers.Builder, platformOs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(platformOs), 0)
}
func StructMetadataAddPlatformAbi(builder *flatbuffers.Builder, platformAbi flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(platformAbi), 0)
}
func StructMetadataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
