// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package channel

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SignalWrite struct {
	_tab flatbuffers.Table
}

func GetRootAsSignalWrite(buf []byte, offset flatbuffers.UOffsetT) *SignalWrite {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SignalWrite{}
	x.Init(buf, n+offset)
	return x
}

func FinishSignalWriteBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSignalWrite(buf []byte, offset flatbuffers.UOffsetT) *SignalWrite {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SignalWrite{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSignalWriteBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SignalWrite) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SignalWrite) Table() flatbuffers.Table {
	return rcv._tab
}

/// Vector encoded Signals (scalar).
func (rcv *SignalWrite) Signal(obj *Signal, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 16
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SignalWrite) SignalLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// Vector encoded Signals (scalar).
func SignalWriteStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SignalWriteAddSignal(builder *flatbuffers.Builder, signal flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(signal), 0)
}
func SignalWriteStartSignalVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(16, numElems, 8)
}
func SignalWriteEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
