// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package notify

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BinarySignal struct {
	_tab flatbuffers.Table
}

func GetRootAsBinarySignal(buf []byte, offset flatbuffers.UOffsetT) *BinarySignal {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BinarySignal{}
	x.Init(buf, n+offset)
	return x
}

func FinishBinarySignalBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBinarySignal(buf []byte, offset flatbuffers.UOffsetT) *BinarySignal {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BinarySignal{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBinarySignalBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BinarySignal) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BinarySignal) Table() flatbuffers.Table {
	return rcv._tab
}

/// Signal UID.
func (rcv *BinarySignal) Uid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// Signal UID.
func (rcv *BinarySignal) MutateUid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

/// Signal Value (binary).
func (rcv *BinarySignal) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BinarySignal) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BinarySignal) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Signal Value (binary).
func (rcv *BinarySignal) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func BinarySignalStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BinarySignalAddUid(builder *flatbuffers.Builder, uid uint32) {
	builder.PrependUint32Slot(0, uid, 0)
}
func BinarySignalAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func BinarySignalStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BinarySignalEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
